project:
  type: website
  output-dir: docs

website:
  title: "Vincent L. Ott"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: about
      - href: publications.qmd
        text: publications
      - href: raincloudplots.qmd
        text: raincloud plots
      - href: game.qmd
        text: "ðŸ§ªðŸ•¹"
    right: 
      - href: siteDetails.qmd
        text: "site details"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
